version: "3.7"
services:
  
  jupyter-notebook:
    image: jupyter/base-notebook:python-3.7.3
    ports:
      - 80:8888
    volumes:
      - ../data:/home/jovyan/work/
      - ../config:/home/jovyan/work/config
# If want to poweruser to get something system package , you can open this setting to get system admin permission , but this option will make this developement environment not safely
#    environment: 
#      - GRANT_SUDO=yes
#    user: root
    command: start-notebook.sh --NotebookApp.token=''
